version: "3.9"
name: llm-qa

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    # 挂载你已经准备好的向量库目录（宿主机 ./chroma -> 容器 /app/chroma）
    volumes:
      - ./chroma:/app/chroma
    ports:
      - "8000:8000"
    restart: unless-stopped